/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skuskapenka;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Mino
 */
public class Skusanie extends javax.swing.JFrame {
    int indexSlova;
    ArrayList<String> slovenske = new ArrayList<>();
    ArrayList<String> anglicke = new ArrayList<>();
    /**
     * Creates new form Skusanie
     */;
    /**
     * Creates new form Skusanie
     */
    public Skusanie() {
        initComponents();
        naplnSlova();
    }
    
    //HashMap<int, String> mapka = new HashMap<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        slovoTF = new javax.swing.JTextField();
        slovoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spravneBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skusanie");

        slovoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slovoTFActionPerformed(evt);
            }
        });

        slovoLabel.setText("XX");

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spravneBut.setText("spravne");
        spravneBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spravneButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slovoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(slovoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spravneBut)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slovoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slovoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(spravneBut))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slovoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slovoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slovoTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        mapka.get(slovoTF.getText());
       indexSlova = randomizeInt(slovenske);
       slovoLabel.setText(slovenske.get(indexSlova));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spravneButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spravneButActionPerformed
        if(slovoTF.getText().equals(anglicke.get(indexSlova)))
            System.out.println("SPRAVNE");
        else 
            System.err.println("zle");
    }//GEN-LAST:event_spravneButActionPerformed
    
    private void naplnSlova(){
        slovenske.add("jeden");
        anglicke.add("one");
        slovenske.add("dva");
        anglicke.add("two");
        slovenske.add("tri");
        anglicke.add("three");
        slovenske.add("styri");
        anglicke.add("four");
        slovenske.add("pat");
        anglicke.add("five");    
        slovenske.add("sest");
        anglicke.add("six"); 
        slovenske.add("sedem");
        anglicke.add("seven"); 
        slovenske.add("osem");
        anglicke.add("eight");         
    }
    /**
     * @param args the command line arguments
     */
    
    public int getValue(ArrayList list, String value){
        return list.indexOf(value);
    }
    
    public String randomizeString(ArrayList list){
        return list.get(((int)(Math.random() * list.size()))).toString();
    }
    
    public int randomizeInt(ArrayList list){
        return (int)(Math.random() * list.size());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skusanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skusanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skusanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skusanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Skusanie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel slovoLabel;
    private javax.swing.JTextField slovoTF;
    private javax.swing.JButton spravneBut;
    // End of variables declaration//GEN-END:variables
}
